language: java
jdk:
 - oraclejdk10
script:
- cd techvideo/
- ./mvnw clean install -B
- ./mvnw test -B
notifications:
  email: false
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
